### PR TITLE
(DEMO PR) Make the site the best ever

### PR DESCRIPTION
**Pull request by jeffmaher**
_DON'T MERGE THIS: Use for demo purposes_

Makes the tag line for the site indicate its new status based on its quality.

### CODE REVIEW

**Comment by jeffmaher** [comment]
Blah blah blah

**Review by skcain — CHANGES_REQUESTED** [review]
This title is terrible! :)

**Review by stateCasey — COMMENTED** [review]
SKain clearly disregards the developer's opinion of this site

**Comment by skcain** [comment]
@skcain kindly requests that the developers make the title rotate through several phrases and appear to sparkle (see MySpace circa 2004 for inspiration)

**Pull request closed without merging**
