### PR TITLE
add language filter to search results

### PR DESCRIPTION
**Pull request by cathydeng**
Screen Shot 2022-07-13 at 10 27 36 PM

my hunch is that this list is too long and it's not worth it to display all, b/c many of these languages would filter results down to zero (even selecting spanish filters down results significantly) so we may want to make a call on what to include/exclude. also, i'm realizing that we're not even displaying languages on the result detail page, which is slightly awk.

### CODE REVIEW

**Review by jlhogan — APPROVED** [review]
approved, from a code perspective. but agree that we should get product decision around actual usefulness

**Review by amdarnell7 — APPROVED** [review]
I am actually okay with the length of this list but I would tag @skcain as well to push back if she disagrees.

**Comment by cathydeng** [comment]
@skcain @admoorgit that solution (displaying the numbers upfront) adds more complexity bc it would involve running a search on all the diff filter values and counting the results, which would take additional work. it could also be awk, bc people could select other filters, so to be proactive w counts we’d prob also need to update the ui to perform searches upon toggling checkboxes instead of upon clicking the apply button

the simplest/cheapest solutions would be to have a heuristic for what values we display and have that be informed by data - for example, the 5 most commonly supported languages in the ladders data, or wait and see the 5 most clicked-on languages (which we can glean from analytics) after a lil bit of use

**Comment by admoorgit** [comment]
Late to the party, but the length doesn't bug me. Also we should def add languages to the detail page (my bad on overlooking it — but will add in the same area as pop served + accessibility. I kinda like @skcain's idea about making zero result items unelectable (grayed out) — @jlhogan is this something we could look into?

**Pull request merged**
