### PR TITLE
Move privacy commitment into footer

### PR DESCRIPTION
**Pull request by jlhogan**

### CODE REVIEW

**Review by amdarnell7 — APPROVED** [review]

**Review by jeffmaher — APPROVED** [review]

**Comment by jeffmaher** [comment]
@admoorgit : How does this look to you?

**Review by admoorgit — CHANGES_REQUESTED** [review]
Let's shrink the BHA logo mark a little — down to 40 x 40px please. Otherwise looks great!

**Review by jeffmaher — CHANGES_REQUESTED** [review]
Needs a bit of tweaking on mobile:
image

**Review by admoorgit — APPROVED** [review]
Mobile looks good. And this will include the tweak to make the BHA icon smaller, yeah? 40x40 instead of 55x55?

**Comment by jlhogan** [comment]
```
Mobile looks good. And this will include the tweak to make the BHA icon smaller, yeah? 40x40 instead of 55x55?
``` 
WHOOPS yes just added that back in, sorry !

**Comment by amdarnell7** [comment]
This looks good to me.

**Review by jeffmaher — APPROVED** [review]
LGTM!

**Pull request merged**
