### PR TITLE
Adds react app with initial dependencies (USWDS, leaflet)

### PR DESCRIPTION
**Pull request by jlhogan**

### CODE REVIEW

**Comment by cathydeng** [comment]
sweet!! it's funky that the node modules are checked in even tho they're in the gitignore - maybe something w/ the git cache? can you see if deleting `node_modules` or `git rm -r --cached .` gets em to actually be ignored?

**Comment by jeffmaher** [comment]
> sweet!! it's funky that the node modules are checked in even tho they're in the gitignore - maybe something w/ the git cache? can you see if deleting `node_modules` or `git rm -r --cached .` gets em to actually be ignored?

I think the `.gitignore` just needs to be moved up to the base directory `/`. Right now, it's inside `/app`, and `node_modules` is in `/`.

**Review by jeffmaher — CHANGES_REQUESTED** [review]
On the note of what @cathydeng said: 

I think the `.gitignore` files just needs to be moved up to the base directory `/`. Right now, it's inside `/app`, and `node_modules` is in `/`.

**Comment by jlhogan** [comment]
yes good eye didn't think about that, the gitignore was from create react app bootstrapping, will move! 
also @jeffmaher what can you tell me about this required release label that's causing a failure in the pipeline?

**Comment by cathydeng** [comment]
i don't have the ability to approve this in the gh ui, but LGTM! 💖

**Review by jeffmaher — APPROVED** [review]

**Pull request merged**
